### ISSUE TITLE
Bluetooth settings access doesn't seem to be working on iOS 10

### ISSUE THREAD

**Issue by jlubeck** [pascalbros/PAPermissions#17]
When tapping on the Enable button when i have bluetooth off, i'm not taken to the settings screen. It works fine on iOS 9

**Comment by pascalbros** [comment]
Unfortunately this is not possible anymore in iOS 10 [source](https://forums.developer.apple.com/thread/51835) 

Anyway we can show a popup with some instructions or a custom message taken from the app's plist.

Let's discuss about it.

**Comment by pascalbros** [comment]
I have a better idea:

Instead of doing this:

```
public override func defaultAction() {
        if #available(iOS 9, *) {
            let url = URL(string: "prefs:root=Bluetooth")!
            UIApplication.shared.openURL(url)
        } else {
            let url = URL(string: "prefs:root=General&path=Bluetooth")!
            UIApplication.shared.openURL(url)
        }
    }
```

We can workaround this with:

```
public override func defaultAction() {
        if #available(iOS 10, *) {
            self.managerBLE = CBCentralManager(delegate: self, queue: nil, options: [CBCentralManagerOptionShowPowerAlertKey: true])
        }else if #available(iOS 9, *) {
            let url = URL(string: "prefs:root=Bluetooth")!
            UIApplication.shared.openURL(url)
        } else {
            let url = URL(string: "prefs:root=General&path=Bluetooth")!
            UIApplication.shared.openURL(url)
        }
    }
```

When the user tap the "Enable" button, the pop-up "Turn On Bluetooth to Allow "Your App" to connect to Accessories" will come up.
I think this is an elegant workaround and fully supported by Apple.

If I don't receive a feedback within 2 days, I'll push the update and close the issue.

Let me know.
