### ISSUE TITLE
Motion Fitness cannot be set

### ISSUE THREAD

**Issue by evermeer** [pascalbros/PAPermissions#18]
Motion Fitness is only detected after pressing the enable butten
When it's disabled in settings and you press the Enable button, nothing happens.
I expect it to go to the Settings app.
Xcode 8, iOS 10

**Comment by joeblau** [comment]
This is a security feature of iOS.  For all items in HealthKit,  you can only verify if they are available, but you can't verify whether they are enabled or not though public API's.  Because of that, you can never know if motion activity is set -- If  you think this should be changed. please file a [Radar](http://bugreport.apple.com).
