### ISSUE TITLE
Feature request: Disable the custom option

### ISSUE THREAD

**Issue by evermeer** [pascalbros/PAPermissions#19]
It would be nice if it was possible to disable the 'custom option'. Currently you can only enable it and there is no way to disable it

**Comment by pascalbros** [comment]
Hi @evermeer 
Can you be more specific? Instead of the "checkmark", a "Disable" button?

**Comment by evermeer** [comment]
@pascalbros That could be an option. Or you could make the checkmark pushable. When you press the check you could ask if the user want to turn it off. And then maybe also for the other options (ask if the user wants to go to the settings)
Im not sure yet what would be the best user interaction for this.

**Comment by pascalbros** [comment]
Well, I don't think this is a good practice, because nobody will tap it, I mean, it is just a checkmark, not a button.
My idea is to add a `canBeDisabled` ivar to the `PAPermissionsCheck` class and change the button in a checkmark if it is false or in a "Enable" button otherwise.
In this way, you can handle the behavior by overriding the "defaultAction" method.

Let me know.

**Comment by evermeer** [comment]
Ah, that sounds good!

**Comment by pascalbros** [comment]
Check the commit https://github.com/pascalbros/PAPermissions/commit/43b7aa65c69f4cd71075590cbe4039f0d88a3ed6

Cheers!
